[package]
name = "cli"
version = "0.1.0"
authors = ["Jean-Baptiste Trystram <jbtrystram@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "1.0"
reqwest = { version = "0.11", features = ["blocking"] }
clap = "2.33.3"

strum = "0.20"
strum_macros = "0.20"

serde_json = "1.0.64"
tempfile = "3.2.0"