[package]
name = "drg"
version = "0.3.0"
authors = ["Jean-Baptiste Trystram <jbtrystram@redhat.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
description = "A command line tool to interact with a drogue-cloud instance."
repository = "https://github.com/drogue-iot/drg/"
homepage = "https://drogue.io/"


categories = ["command-line-utilities"]

[dependencies]

anyhow = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
clap = "2.33.3"

oauth2 = "3.0"

simple_logger = "1.11.0"
log = "0.4.13"

strum = "0.20"
strum_macros = "0.18"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
colored_json = "2"
tempfile = "3.2.0"

tiny_http = "0.6.2"
qstring = "0.7.2"

url = { version = "2.2.1",  features = ["serde"] }
chrono = { version = "0.4", features = ["serde"]}

webbrowser = "0.5.5"
