[package]
name = "drg"
version = "0.1.1"
authors = ["Jean-Baptiste Trystram <jbtrystram@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
clap = "2.33.3"

oauth2 = "3.0"

strum = "0.20"
strum_macros = "0.20"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.2.0"

tiny_http = "0.8.0"
qstring = "0.7.2"

url = { version = "2.2.1",  features = ["serde"] }
chrono = { version = "0.4", features = ["serde"]}