on:
  release:
    branches:
      - main
    types: [created]
name: Publish release
jobs:
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install build tools
        run: sudo apt-get update; DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install build-essential curl tzdata 
      - name: Install openssl
        run: sudo apt install -y libssl-dev pkg-config
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename
        run: mv ./target/release/drg ./target/release/drg-linux
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: ./target/release/drg-linux
          repo-token: ${{ secrets.GITHUB_TOKEN }}

