on:
  release:
    branches:
      - main
    types: [created]
name: Publish release
jobs:
  release_linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Install build tools
        run: sudo apt-get update; DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install build-essential curl tzdata 
      - name: Install openssl
        run: sudo apt install -y libssl-dev pkg-config
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv ./target/release/drg drg-linux
          hub release edit -m "" -a drg-linux ${GITHUB_REF/refs\/tags\//}
